#ifndef ALTTPCOLORFIX_H
#define ALTTPCOLORFIX_H

#define BINARY_IMAGE_FORMAT_RGBA32 0
#define BINARY_IMAGE_FORMAT_RGBA16 1
#define BINARY_IMAGE_FORMAT_IA16 2
#define BINARY_IMAGE_FORMAT_IA8 3
#define BINARY_IMAGE_FORMAT_IA4 4
#define BINARY_IMAGE_FORMAT_I8 5
#define BINARY_IMAGE_FORMAT_I4 6
#define BINARY_IMAGE_FORMAT_CI8 7
#define BINARY_IMAGE_FORMAT_CI4 8
#define BINARY_IMAGE_FORMAT_1BPP 9

#define RGBA32_PIXEL_SIZE 4
#define RGBA16_PIXEL_SIZE 2
#define IA16_PIXEL_SIZE 2
#define IA8_PIXEL_SIZE 1

int check_arguments(int argc);
png_color get_fixed_color(png_color color);

#endif